name: Publish Python Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write # Required for trusted publishing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Or a specific version like '3.11'

      - name: Run publish script
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }} # Only if not using Trusted Publishers
        run: bash ./publish.sh # Call bash directly, as uv is installed globally
